### ISSUE TITLE
failure with GHC 8.2

### ISSUE THREAD

**Issue by clinty** [blamario/monoid-subclasses#27]
I don't have a good reason to support builds with GHC 8.2, but maybe you could tweak some bounds so that an older version of monoid-subclasses gets selected on those systems.

```src/Data/Semigroup/Factorial.hs:423:94: error:
    • Could not deduce (Semigroup b) arising from a use of ‘<>’
      from the context: (Factorial a, Monoid b, Monad m)
        bound by the type signature for:
                   mapM :: forall a b (m :: * -> *).
                           (Factorial a, Monoid b, Monad m) =>
                           (a -> m b) -> a -> m b
        at src/Data/Semigroup/Factorial.hs:422:1-66
      Possible fix:
        add (Semigroup b) to the context of
          the type signature for:
            mapM :: forall a b (m :: * -> *).
                    (Factorial a, Monoid b, Monad m) =>
                    (a -> m b) -> a -> m b
    • In the first argument of ‘Monad.liftM2’, namely ‘(<>)’
      In the first argument of ‘(.)’, namely ‘Monad.liftM2 (<>)’
      In the second argument of ‘(.)’, namely ‘Monad.liftM2 (<>) . f’
    |
423 | mapM f = ($ return mempty) . appEndo . Data.Semigroup.Factorial.foldMap (Endo . Monad.liftM2 (<>) . f)
    |                                                                                              ^^^^
```

**Comment by clinty** [comment]
Closing because I don't actually care about this.
